/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as _rootUnifiedRouteImport } from './routes/__root-unified.tsx'
import { Route as StatusRouteImport } from './routes/status.tsx'
import { Route as LegalRouteImport } from './routes/legal.tsx'
import { Route as ComponentsRouteImport } from './routes/components.tsx'
import { Route as RunsRouteRouteImport } from './routes/runs/route.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as RunsIndexRouteImport } from './routes/runs/index.tsx'
import { Route as RunsRunIndexRouteImport } from './routes/runs/$run.$index.tsx'

const _rootUnifiedRoute = _rootUnifiedRouteImport.update({
  id: '/__root-unified',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRouteRoute = RunsRouteRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRouteRoute,
} as any)
const RunsRunIndexRoute = RunsRunIndexRouteImport.update({
  id: '/$run/$index',
  path: '/$run/$index',
  getParentRoute: () => RunsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/legal': typeof LegalRoute
  '/status': typeof StatusRoute
  '/runs/': typeof RunsIndexRoute
  '/runs/$run/$index': typeof RunsRunIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/legal': typeof LegalRoute
  '/status': typeof StatusRoute
  '/runs': typeof RunsIndexRoute
  '/runs/$run/$index': typeof RunsRunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteRouteWithChildren
  '/__root-unified': typeof _rootUnifiedRoute
  '/components': typeof ComponentsRoute
  '/legal': typeof LegalRoute
  '/status': typeof StatusRoute
  '/runs/': typeof RunsIndexRoute
  '/runs/$run/$index': typeof RunsRunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs'
    | '/components'
    | '/legal'
    | '/status'
    | '/runs/'
    | '/runs/$run/$index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/legal' | '/status' | '/runs' | '/runs/$run/$index'
  id:
    | '__root__'
    | '/'
    | '/runs'
    | '/__root-unified'
    | '/components'
    | '/legal'
    | '/status'
    | '/runs/'
    | '/runs/$run/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRouteRoute: typeof RunsRouteRouteWithChildren
  _rootUnifiedRoute: typeof _rootUnifiedRoute
  ComponentsRoute: typeof ComponentsRoute
  LegalRoute: typeof LegalRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root-unified': {
      id: '/__root-unified'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _rootUnifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRouteRoute
    }
    '/runs/$run/$index': {
      id: '/runs/$run/$index'
      path: '/$run/$index'
      fullPath: '/runs/$run/$index'
      preLoaderRoute: typeof RunsRunIndexRouteImport
      parentRoute: typeof RunsRouteRoute
    }
  }
}

interface RunsRouteRouteChildren {
  RunsIndexRoute: typeof RunsIndexRoute
  RunsRunIndexRoute: typeof RunsRunIndexRoute
}

const RunsRouteRouteChildren: RunsRouteRouteChildren = {
  RunsIndexRoute: RunsIndexRoute,
  RunsRunIndexRoute: RunsRunIndexRoute,
}

const RunsRouteRouteWithChildren = RunsRouteRoute._addFileChildren(
  RunsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRouteRoute: RunsRouteRouteWithChildren,
  _rootUnifiedRoute: _rootUnifiedRoute,
  ComponentsRoute: ComponentsRoute,
  LegalRoute: LegalRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
